### PR TITLE
refactor: make zot 'go get'-able

### PR DESCRIPTION
**Pull request by rchincha**
1) github.com/jtblin/go-ldap-client is an abandoned project and not keeping
up with go modules, so pull that code in (single file, BSD license)

2) minor refactor ldap as a result of 1)

3) commit docs which should change only with dist-spec changes

4) update go.mod

### CODE REVIEW

**Comment by tych0** [comment]
Might be nice to have these as separate commits since they're separate logical changes.

Other than that, if the LDAP library is abandoned, perhaps we should look into switching to a different one?

**Comment by rchincha** [comment]
> 
> 
> Might be nice to have these as separate commits since they're separate logical changes.
> 
> Other than that, if the LDAP library is abandoned, perhaps we should look into switching to a different one?

This LDAP library was the easiest one to use in terms of interfaces. We could explore that.

**Comment by tych0** [comment]
> Ironically, it is the LDAP library that is breaking the "go get" behavior we want, so a cascade effect :\

Ok, but can't we split the commits? I don't see how it's related.

**Comment by rchincha** [comment]
> 
> 
> > Ironically, it is the LDAP library that is breaking the "go get" behavior we want, so a cascade effect :\
> 
> Ok, but can't we split the commits? I don't see how it's related.

I can probably do two splits - 1) ldap + go.mod changes, and 2) the doc changes.

**Comment by rchincha** [comment]
> 
> 
> > > Ironically, it is the LDAP library that is breaking the "go get" behavior we want, so a cascade effect :\
> > 
> > 
> > Ok, but can't we split the commits? I don't see how it's related.
> 
> I can probably do two splits - 1) ldap + go.mod changes, and 2) the doc changes.

Do you want separate PRs for these though?

**Comment by tych0** [comment]
Nah, this lgtm!

**Pull request merged**
