### PR TITLE
JSON output option for compliance checks

### LINKED ISSUE #40: html/json reporting for compliance checks
As per discussion in [1], there is a requirement to generate a compliance check report in html or json.

zot uses goconvey [2] for driving unit tests and by extension, the compliance checks. goconvey has a reporting [3] package that could help with this.

References:
[1] https://groups.google.com/a/opencontainers.org/forum/m/#!topic/dev/JCpfBI-_woQ
[2] https://github.com/smartystreets/goconvey
[3] https://godoc.org/github.com/smartystreets/goconvey/convey/reporting

### PR DESCRIPTION
**Pull request by jdolitsky**
Fixes #40.

This adds a `--json` flag which will output the raw goconvey results as minified JSON for the compliance subcommand. 

This can then be used by some other tool to build out an HTML report (or we can add `--html` flag later which leverages this data).

Example output:
```
$ bin/zot compliance -H 0.0.0.0 -P 8080 --json | jq
[
  {
    "Assertions": [],
    "Depth": 1,
    "File": "<unknown file>",
    "Line": -1,
    "Output": "",
    "Title": "Make API calls to the controller"
  },
  {
    "Assertions": [
      {
        "Actual": "",
        "Error": null,
        "Expected": "",
        "Failure": "",
        "File": "",
        "Line": 0,
        "Skipped": false,
        "StackTrace": ""
      },
      {
        "Actual": "",
        "Error": null,
        "Expected": "",
        "Failure": "",
        "File": "",
        "Line": 0,
        "Skipped": false,
        "StackTrace": ""
      }
    ],
    "Depth": 2,
    "File": "<unknown file>",
    "Line": -1,
    "Output": "\nCheck version",
    "Title": "Check version"
  },
  {
    "Assertions": [
      {
        "Actual": "",
        "Error": null,
        "Expected": "",
        "Failure": "",
        "File": "",
        "Line": 0,
        "Skipped": false,
        "StackTrace": ""
      },
      {
        "Actual": "",
        "Error": null,
...
```

In the case of a failed test case, the `Failure` field will contain the failed assertion, for example:
```
...
      {
        "Actual": "200",
        "Error": null,
        "Expected": "404",
        "Failure": "Expected: '404'\nActual:   '200'\n(Should be equal)",
        "File": "<unknown file>",
        "Line": -1,
        "Skipped": false,
        "StackTrace": "goroutine 1 [running]:\n\t/Users/jdolitsky/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190710185942-9d28bd7c0945/convey/reporting/reports.go:143 +0x6d\n\t/Users/jdolitsky/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190710185942-9d28bd7c0945/convey/reporting/reports.go:103
...
```

Also:
- Exit 1 if compliance tests fail
- Refactor tests to allow random port for test server (vs. 8080 which may be in use) using freeport library

### CODE REVIEW

**Comment by rchamarthy** [comment]
@jdolitsky Looks like there are some conflicts, could you rebase and push the PR again. Thank you for your contribution.

**Comment by jdolitsky** [comment]
@rchamarthy happy to contribute :) I'm looking forward to continue expanding the zot compliance suite to be general-purpose enough to run against any OCI registry.

I've rebased, squashed, and Travis tests are passing. Let me know if anything else needed. Thanks

**Comment by rchincha** [comment]
LGTM

We can build on this PR to improve on brevity and pretty-output.

**Comment by jdolitsky** [comment]
@rchincha accidentally closed vs merged?

**Pull request merged**
