### PR TITLE
go.mod: upgrade module deps

### PR DESCRIPTION
**Pull request by rchincha**
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>

### CODE REVIEW

**Comment by rchincha** [comment]
@peusebiu moved containers/image to upstream. We need to pass in flags to make squashfs work.

**Comment by tych0** [comment]
You mention needing to pass flags, which patch actually passes those flags?

**Comment by rchincha** [comment]
> 
> 
> You mention needing to pass flags, which patch actually passes those flags?

@peusebiu needs to fix his part of zot code to do that. So would ask to take ownership of this PR for that.

**Review by shimish2 — APPROVED** [review]
lgtm

**Pull request merged**
