### PR TITLE
Add binary type in binary information

### PR DESCRIPTION
**Pull request by shimish2**
``` 
{"level":"info","distribution-spec":"0.1.0-dev","commit":"extended-v1.1.12-21-gfaf4ad8-dirty","time":"2021-02-12T17:00:14-08:00","message":"version"}
``` 

``` 
{"level":"info","distribution-spec":"0.1.0-dev","commit":"minimal-v1.1.13-2-g873801e","time":"2021-02-12T17:01:34-08:00","message":"version"}
```

### CODE REVIEW

**Comment by rchincha** [comment]
Remove the "extended" in the full build.

**Review by mikemccracken — COMMENTED** [review]
seems a little odd to overload "Commit" here, can we add it as a separate value and just pass in two `-X` args?

**Comment by shimish2** [comment]
> seems a little odd to overload "Commit" here, can we add it as a separate value and just pass in two `-X` args?

ok, i will add new var here

**Comment by shimish2** [comment]
> Remove the "extended" in the full build.

ok, i will do

**Comment by rchincha** [comment]
Ok, so as per @mikemccracken 's comment, have two fields - Commit and BinaryType

**Comment by shimish2** [comment]
> Ok, so as per @mikemccracken 's comment, have two fields - Commit and BinaryType

Yes made those changes and now output look like this 

``` 
[shimish2@shimish2-bld zot]$ bin/zot-minimal --version 
{"level":"info","distribution-spec":"0.1.0-dev","commit":"v1.1.13-6-ge6c5581","binary-type":"minimal","time":"2021-05-04T11:12:31-07:00","message":"version"}
[shimish2@shimish2-bld zot]$ bin/zot --version 
{"level":"info","distribution-spec":"0.1.0-dev","commit":"v1.1.13-6-ge6c5581","binary-type":"extended","time":"2021-05-04T11:12:44-07:00","message":"version"}
```

and upon starting server it looks like that 

``` 
{"level":"info","params":{"Version":"0.1.0-dev","Commit":"v1.1.13-6-ge6c5581","BinaryType":"extended","Storage":{"RootDirectory":"/tmp/zot","GC":true,"Dedupe":true},"HTTP":{"Address":"127.0.0.1","Port":"8080","TLS":null,"Auth":null,"Realm":"","AllowReadAccess":false,"ReadOnly":false},"Log":{"Level":"debug","Output":""},"Extensions":null},"caller":"/local/shimish2/go/src/github.com/anuvu/zot/pkg/api/controller.go:45","time":"2021-05-04T11:14:35.531952179-07:00","message":"configuration settings"}
``` 

```
[shimish2@shimish2-bld zot]$ bin/zot-minimal serve examples/config-minimal.json 
{"level":"info","params":{"Version":"0.1.0-dev","Commit":"v1.1.13-6-ge6c5581","BinaryType":"minimal","Storage":{"RootDirectory":"/tmp/zot","GC":true,"Dedupe":true},"HTTP":{"Address":"127.0.0.1","Port":"8080","TLS":null,"Auth":null,"Realm":"","AllowReadAccess":false,"ReadOnly":false},"Log":{"Level":"debug","Output":""},"Extensions":null},"caller":"/local/shimish2/go/src/github.com/anuvu/zot/pkg/api/controller.go:45","time":"2021-05-04T11:15:02.794262827-07:00","message":"configuration settings"}
```

**Review by mikemccracken — APPROVED** [review]
great, thanks!

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
