### PR TITLE
ci/cd: unit test hangs for a long time intermittently closes #286

### LINKED ISSUE #286: ci/cd: unit test hangs for a long time intermittently
https://github.com/anuvu/zot/runs/4243958797?check_suite_focus=true

```
coverage: 16.4% of statements in ./...
panic: test timed out after 10m0s

goroutine 1192 [running]:
testing.(*M).startAlarm.func1()
testing/testing.go:1700 +0x11f
created by time.goFunc
time/sleep.go:180 +0x52
```

### PR DESCRIPTION
**Pull request by adodon2go**
Signed-off-by: Alexei Dodon <adodon@cisco.com>

The fix is below two lines (the rest of PR is refactoring):
https://github.com/adodon2go/zot/blob/test-issue-286/pkg/api/controller_test.go#L2382
https://github.com/adodon2go/zot/blob/test-issue-286/pkg/api/controller_test.go#L2770

### CODE REVIEW

**Comment by rchincha** [comment]
Still fails.

```
RESTY 2021/11/22 09:01:07 WARNING - Using Basic Auth in HTTP mode is not secure.
coverage: 16.5% of statements in ./...
panic: test timed out after 10m0s

goroutine 1182 [running]:
testing.(*M).startAlarm.func1()
	testing/testing.go:1700 +0x11f
created by time.goFunc
	time/sleep.go:180 +0x52

**Comment by adodon2go** [comment]
> Still fails.
> 
> ```
> RESTY 2021/11/22 09:01:07 WARNING - Using Basic Auth in HTTP mode is not secure.
> coverage: 16.5% of statements in ./...
> panic: test timed out after 10m0s
> 
> goroutine 1182 [running]:
> testing.(*M).startAlarm.func1()
> 	testing/testing.go:1700 +0x11f
> created by time.goFunc
> 	time/sleep.go:180 +0x52
> ```

Yes, but now in TestparallelRequests. I will try to fix that together with other issue I have https://github.com/anuvu/zot/issues/241 as I have to touch that test anyway.

**Comment by adodon2go** [comment]
When tried to reproduce the issue locally on some slow machine I saw also a panic related to this line 
https://github.com/anuvu/zot/blob/main/pkg/cli/cve_cmd_test.go#L333
Increasing the timer fixed the issue, but we need a smart way of detecting when trivy-db is available regardless of how slow the system we run tests is.

**Comment by adodon2go** [comment]
Test failed 3rd time dur to a DATA RACE:
`
2021-11-26T21:16:28.8806966Z === RUN   TestSyncBadTLS
2021-11-26T21:16:28.8807242Z 
2021-11-26T21:16:28.8810510Z   Verify sync TLS feature ✔{"level":"info","params":{"Version":"1.0.0-dev","GoVersion":"","Commit":"","BinaryType":"","AccessControl":null,"Storage":{"RootDirectory":"/tmp/oci-src-repo-test372821520","Dedupe":true,"GC":true,"StorageDriver":null,"SubPaths":null},"HTTP":{"Address":"127.0.0.1","Port":"34641","TLS":{"Cert":"../../../test/data/server.cert","Key":"../../../test/data/server.key","CACert":"../../../test/data/ca.crt"},"Auth":null,"RawAccessControl":null,"Realm":"","AllowReadAccess":false,"ReadOnly":false},"Log":{"Level":"debug","Output":"","Audit":""},"Extensions":null},"goroutine":867,"caller":"github.com/anuvu/zot/pkg/api/controller.go:77","time":"2021-11-26T21:15:49.255368179Z","message":"configuration settings"}
2021-11-26T21:16:28.8816241Z {"level":"error","error":"writing blob: rename /tmp/oci-dest-repo-test415084718/zot-test/.sync/89db0fd9-d848-4b39-a402-526786d6a457/zot-test/oci-put-blob608662069 /tmp/oci-dest-repo-test415084718/zot-test/.sync/89db0fd9-d848-4b39-a402-526786d6a457/zot-test/blobs/sha256/2d473b07cdd5f0912cd6f1a703352c82b512407db6b05b43f2553732b55df3bc: permission denied","goroutine":770,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:404","time":"2021-11-26T21:15:49.712583703Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:404","time":"2021-11-26T21:15:49.712605503Z","message":"error while copying image 127.0.0.1:38993/zot-test:0.0.1 to /tmp/oci-dest-repo-test415084718/zot-test/.sync/89db0fd9-d848-4b39-a402-526786d6a457/zot-test:0.0.1"}
2021-11-26T21:16:28.8822455Z {"level":"error","error":"writing blob: rename /tmp/oci-dest-repo-test415084718/zot-test/.sync/89db0fd9-d848-4b39-a402-526786d6a457/zot-test/oci-put-blob608662069 /tmp/oci-dest-repo-test415084718/zot-test/.sync/89db0fd9-d848-4b39-a402-526786d6a457/zot-test/blobs/sha256/2d473b07cdd5f0912cd6f1a703352c82b512407db6b05b43f2553732b55df3bc: permission denied","goroutine":770,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:483","time":"2021-11-26T21:15:49.712715502Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:483","time":"2021-11-26T21:15:49.712728402Z","message":"sync exited with error, stopping it..."}
2021-11-26T21:16:28.8878907Z ==================
2021-11-26T21:16:28.8879290Z WARNING: DATA RACE
2021-11-26T21:16:28.8879724Z Write at 0x000004bae4d0 by goroutine 10:
2021-11-26T21:16:28.8880565Z   github.com/anuvu/zot/pkg/log.NewLogger()
2021-11-26T21:16:28.8881099Z       github.com/anuvu/zot/pkg/log/log.go:23 +0x9a
2021-11-26T21:16:28.8881637Z   github.com/anuvu/zot/pkg/api.NewController()
2021-11-26T21:16:28.8882236Z       github.com/anuvu/zot/pkg/api/controller.go:42 +0x1a4
2021-11-26T21:16:28.8882956Z   github.com/anuvu/zot/pkg/extensions/sync_test.TestSyncBadTLS.func1()
2021-11-26T21:16:28.8883741Z       github.com/anuvu/zot/pkg/extensions/sync_test/sync_test.go:782 +0x1276
2021-11-26T21:16:28.8884498Z   github.com/smartystreets/goconvey/convey.parseAction.func1()
2021-11-26T21:16:28.8885282Z       github.com/smartystreets/goconvey@v1.7.2/convey/discovery.go:89 +0x3d
2021-11-26T21:16:28.8886217Z   github.com/smartystreets/goconvey/convey.(*context).conveyInner()
2021-11-26T21:16:28.8886957Z       github.com/smartystreets/goconvey@v1.7.2/convey/context.go:279 +0x231
2021-11-26T21:16:28.8887751Z   github.com/smartystreets/goconvey/convey.rootConvey.func1()
2021-11-26T21:16:28.8888547Z       github.com/smartystreets/goconvey@v1.7.2/convey/context.go:112 +0x1d7
2021-11-26T21:16:28.8889268Z   github.com/jtolds/gls.(*ContextManager).SetValues.func1()
2021-11-26T21:16:28.8891685Z       github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x5ca
2021-11-26T21:16:28.8892662Z   github.com/jtolds/gls.EnsureGoroutineId.func1()
2021-11-26T21:16:28.8893538Z       github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x45
2021-11-26T21:16:28.8894202Z   github.com/jtolds/gls._m()
2021-11-26T21:16:28.8894730Z       github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x42
2021-11-26T21:16:28.8895344Z   github.com/jtolds/gls.github_com_jtolds_gls_markS()
2021-11-26T21:16:28.8896134Z       github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x44
2021-11-26T21:16:28.8896741Z   github.com/jtolds/gls.addStackTag()
2021-11-26T21:16:28.8897542Z       github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49 +0x175
2021-11-26T21:16:28.8898241Z   github.com/jtolds/gls.EnsureGoroutineId()
2021-11-26T21:16:28.8899062Z       github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xcf
2021-11-26T21:16:28.8900168Z   github.com/jtolds/gls.(*ContextManager).SetValues()
2021-11-26T21:16:28.8900838Z       github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x284
2021-11-26T21:16:28.8901721Z   github.com/smartystreets/goconvey/convey.rootConvey()
2021-11-26T21:16:28.8902668Z       github.com/smartystreets/goconvey@v1.7.2/convey/context.go:107 +0x535
2021-11-26T21:16:28.8903571Z   github.com/smartystreets/goconvey/convey.Convey()
2021-11-26T21:16:28.8904266Z       github.com/smartystreets/goconvey@v1.7.2/convey/doc.go:76 +0xe4
2021-11-26T21:16:28.8905028Z   github.com/anuvu/zot/pkg/extensions/sync_test.TestSyncBadTLS()
2021-11-26T21:16:28.8906112Z       github.com/anuvu/zot/pkg/extensions/sync_test/sync_test.go:670 +0xa6
2021-11-26T21:16:28.8906687Z   testing.tRunner()
2021-11-26T21:16:28.8907149Z       testing/testing.go:1193 +0x202
2021-11-26T21:16:28.8907612Z 
2021-11-26T21:16:28.8908191Z Previous read at 0x000004bae4d0 by goroutine 53:
2021-11-26T21:16:28.8908764Z   github.com/rs/zerolog.(*Event).Timestamp()
2021-11-26T21:16:28.8909318Z       github.com/rs/zerolog@v1.26.0/event.go:644 +0x218
2021-11-26T21:16:28.8909967Z   github.com/rs/zerolog.timestampHook.Run()
2021-11-26T21:16:28.8910965Z       github.com/rs/zerolog@v1.26.0/context.go:327 +0x49
2021-11-26T21:16:28.8911862Z   github.com/rs/zerolog.(*timestampHook).Run()
2021-11-26T21:16:28.8912487Z       <autogenerated>:1 +0x26
2021-11-26T21:16:28.8912943Z   github.com/rs/zerolog.(*Event).msg()
2021-11-26T21:16:28.8913595Z       github.com/rs/zerolog@v1.26.0/event.go:134 +0x11d
2021-11-26T21:16:28.8914429Z   github.com/rs/zerolog.(*Event).Msg()
2021-11-26T21:16:28.8915106Z       github.com/rs/zerolog@v1.26.0/event.go:108 +0x364
2021-11-26T21:16:28.8915678Z   github.com/anuvu/zot/pkg/extensions/sync.Run.func1()
2021-11-26T21:16:28.8916315Z       github.com/anuvu/zot/pkg/extensions/sync/sync.go:483 +0x290
2021-11-26T21:16:28.8916677Z 
2021-11-26T21:16:28.8917199Z Goroutine 10 (running) created at:
2021-11-26T21:16:28.8917626Z   testing.(*T).Run()
2021-11-26T21:16:28.8918040Z       testing/testing.go:1238 +0x5d7
2021-11-26T21:16:28.8918524Z   testing.runTests.func1()
2021-11-26T21:16:28.8919202Z       testing/testing.go:1511 +0xa6
2021-11-26T21:16:28.8919635Z   testing.tRunner()
2021-11-26T21:16:28.8920379Z       testing/testing.go:1193 +0x202
2021-11-26T21:16:28.8921066Z   testing.runTests()
2021-11-26T21:16:28.8921647Z       testing/testing.go:1509 +0x612
2021-11-26T21:16:28.8922043Z   testing.(*M).Run()
2021-11-26T21:16:28.8922562Z       testing/testing.go:1417 +0x3b3
2021-11-26T21:16:28.8923064Z   main.main()
2021-11-26T21:16:28.8923427Z       _testmain.go:287 +0x356
2021-11-26T21:16:28.8923796Z 
2021-11-26T21:16:28.8924173Z Goroutine 53 (running) created at:
2021-11-26T21:16:28.8924812Z   github.com/anuvu/zot/pkg/extensions/sync.Run()
2021-11-26T21:16:28.8925538Z       github.com/anuvu/zot/pkg/extensions/sync/sync.go:478 +0x8e4
2021-11-26T21:16:28.8926422Z   github.com/anuvu/zot/pkg/extensions.EnableSyncExtension()
2021-11-26T21:16:28.8927349Z       github.com/anuvu/zot/pkg/extensions/extensions.go:82 +0x377
2021-11-26T21:16:28.8928380Z   github.com/anuvu/zot/pkg/api.(*Controller).Run()
2021-11-26T21:16:28.8929144Z       github.com/anuvu/zot/pkg/api/controller.go:142 +0x2ae6
2021-11-26T21:16:28.8958462Z   github.com/anuvu/zot/pkg/extensions/sync_test.TestSyncPermsDenied.func1.3()
2021-11-26T21:16:28.8959548Z       github.com/anuvu/zot/pkg/extensions/sync_test/sync_test.go:636 +0x38
2021-11-26T21:16:28.8960094Z ==================
2021-11-26T21:16:28.8964627Z {"level":"info","params":{"Version":"1.0.0-dev","GoVersion":"","Commit":"","BinaryType":"","AccessControl":null,"Storage":{"RootDirectory":"/tmp/oci-dest-repo-test188818991","Dedupe":true,"GC":true,"StorageDriver":null,"SubPaths":null},"HTTP":{"Address":"127.0.0.1","Port":"34283","TLS":{"Cert":"../../../test/data/server.cert","Key":"../../../test/data/server.key","CACert":"../../../test/data/ca.crt"},"Auth":null,"RawAccessControl":null,"Realm":"","AllowReadAccess":false,"ReadOnly":false},"Log":{"Level":"debug","Output":"","Audit":""},"Extensions":{"Search":null,"Sync":{"CredentialsFile":"","Registries":[{"URL":"https://127.0.0.1:34641","PollInterval":3600000000000,"Content":[{"Prefix":"zot-test","Tags":{"Regex":".*","Semver":false}}],"TLSVerify":true,"OnDemand":true,"CertDir":""}]},"Metrics":null}},"goroutine":860,"caller":"github.com/anuvu/zot/pkg/api/controller.go:77","time":"2021-11-26T21:15:49.761028909Z","message":"configuration settings"}
2021-11-26T21:16:28.8968623Z {"level":"info","goroutine":860,"caller":"github.com/anuvu/zot/pkg/extensions/extensions.go:54","time":"2021-11-26T21:15:49.764530787Z","message":"CVE config not provided, skipping CVE update"}
2021-11-26T21:16:28.8970353Z {"level":"info","goroutine":860,"caller":"github.com/anuvu/zot/pkg/extensions/extensions.go:66","time":"2021-11-26T21:15:49.764603987Z","message":"Metrics config not provided, skipping Metrics config update"}
2021-11-26T21:16:28.8971941Z {"level":"debug","goroutine":860,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:425","time":"2021-11-26T21:15:49.764699286Z","message":"getting local context"}
2021-11-26T21:16:28.8973774Z {"level":"info","goroutine":861,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:318","time":"2021-11-26T21:15:49.764985085Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:318","time":"2021-11-26T21:15:49.765001684Z","message":"syncing registry: https://127.0.0.1:34641"}
2021-11-26T21:16:28.8976047Z {"level":"debug","goroutine":861,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:322","time":"2021-11-26T21:15:49.765066784Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:322","time":"2021-11-26T21:15:49.765098884Z","message":"getting upstream context"}
2021-11-26T21:16:28.8977779Z {"level":"info","goroutine":860,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:490","time":"2021-11-26T21:15:49.771119747Z","message":"finished setting up sync"}
2021-11-26T21:16:28.9012293Z {"level":"info","goroutine":860,"caller":"github.com/anuvu/zot/pkg/extensions/extensions.go:95","time":"2021-11-26T21:15:49.775943218Z","caller":"github.com/anuvu/zot/pkg/extensions/extensions.go:95","time":"2021-11-26T21:15:49.775957718Z","message":"setting up extensions routes"}
2021-11-26T21:16:28.9015539Z {"level":"error","error":"Get \"https://127.0.0.1:34641/v2/_catalog\": x509: certificate signed by unknown authority","goroutine":861,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:121","time":"2021-11-26T21:15:49.779211798Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:121","time":"2021-11-26T21:15:49.779225698Z","message":"couldn't query https://127.0.0.1:34641/v2/_catalog"}
2021-11-26T21:16:28.9018636Z {"level":"error","error":"Get \"https://127.0.0.1:34641/v2/_catalog\": x509: certificate signed by unknown authority","goroutine":861,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:338","time":"2021-11-26T21:15:49.779311598Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:338","time":"2021-11-26T21:15:49.779325597Z","message":"error while getting upstream catalog, retrying..."}
2021-11-26T21:16:28.9021913Z {"level":"error","error":"Get \"https://127.0.0.1:34641/v2/_catalog\": x509: certificate signed by unknown authority","goroutine":861,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:483","time":"2021-11-26T21:15:49.779391997Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:483","time":"2021-11-26T21:15:49.779402197Z","message":"sync exited with error, stopping it..."}
2021-11-26T21:16:28.9023607Z 2021/11/26 21:15:49 http: TLS handshake error from 127.0.0.1:54902: remote error: tls: bad certificate
2021-11-26T21:16:28.9025321Z {"level":"debug","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:425","time":"2021-11-26T21:15:51.780060548Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:425","time":"2021-11-26T21:15:51.780075048Z","message":"getting local context"}
2021-11-26T21:16:28.9027513Z {"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:318","time":"2021-11-26T21:15:51.780172748Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:318","time":"2021-11-26T21:15:51.780183948Z","message":"syncing registry: https://127.0.0.1:34641"}
2021-11-26T21:16:28.9029613Z {"level":"debug","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:322","time":"2021-11-26T21:15:51.780262347Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:322","time":"2021-11-26T21:15:51.780275547Z","message":"getting upstream context"}
2021-11-26T21:16:28.9031991Z {"level":"error","error":"Get \"https://127.0.0.1:34641/v2/_catalog\": x509: certificate signed by unknown authority","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:121","time":"2021-11-26T21:15:51.794002064Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:121","time":"2021-11-26T21:15:51.794016664Z","message":"couldn't query https://127.0.0.1:34641/v2/_catalog"}
2021-11-26T21:16:28.9034748Z {"level":"error","error":"Get \"https://127.0.0.1:34641/v2/_catalog\": x509: certificate signed by unknown authority","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:338","time":"2021-11-26T21:15:51.794165963Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:338","time":"2021-11-26T21:15:51.794179363Z","message":"error while getting upstream catalog, retrying..."}
2021-11-26T21:16:28.9038906Z {"level":"error","error":"Get \"https://127.0.0.1:34641/v2/_catalog\": x509: certificate signed by unknown authority","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/http_handler.go:55","time":"2021-11-26T21:15:51.794328362Z","caller":"github.com/anuvu/zot/pkg/extensions/sync/http_handler.go:55","time":"2021-11-26T21:15:51.794345462Z","message":"sync http handler: error while syncing in"}
2021-11-26T21:16:28.9042584Z {"level":"info","module":"http","clientIP":"127.0.0.1:37390","method":"POST","path":"/sync","statusCode":500,"latency":"14.465112ms","bodySize":95,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["0"],"User-Agent":["go-resty/1.12.0 (https://github.com/go-resty/resty)"]},"goroutine":881,"caller":"github.com/anuvu/zot/pkg/api/session.go:104","time":"2021-11-26T21:15:51.79456566Z","message":"HTTP API"}
2021-11-26T21:16:28.9044906Z ✔✔{"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/api/routes.go:1277","time":"2021-11-26T21:15:51.79629655Z","message":"manifest not found, trying to get image zot-test:invalid by syncing on demand"}
2021-11-26T21:16:28.9046686Z {"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/extensions.go:129","time":"2021-11-26T21:15:51.796399549Z","message":"syncing image zot-test:invalid"}
2021-11-26T21:16:28.9048509Z {"level":"debug","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:425","time":"2021-11-26T21:15:51.796503848Z","message":"getting local context"}
2021-11-26T21:16:28.9050231Z {"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/on_demand.go:55","time":"2021-11-26T21:15:51.796607648Z","message":"syncing on demand with https://127.0.0.1:34641"}
2021-11-26T21:16:28.9052774Z {"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/on_demand.go:100","time":"2021-11-26T21:15:51.797039245Z","message":"copying image 127.0.0.1:34641/zot-test:invalid to /tmp/oci-dest-repo-test188818991/zot-test/.sync/73237d80-4b5d-46a6-b874-08c62d10a71a/zot-test"}
2021-11-26T21:16:28.9054202Z 2021/11/26 21:15:51 http: TLS handshake error from 127.0.0.1:54906: remote error: tls: bad certificate
2021-11-26T21:16:28.9054967Z 2021/11/26 21:15:51 http: TLS handshake error from 127.0.0.1:54908: remote error: tls: bad certificate
2021-11-26T21:16:28.9057828Z {"level":"error","error":"initializing source docker://127.0.0.1:34641/zot-test:invalid: pinging container registry 127.0.0.1:34641: Get \"https://127.0.0.1:34641/v2/\": x509: certificate signed by unknown authority","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/on_demand.go:113","time":"2021-11-26T21:15:51.826919564Z","message":"error while copying image 127.0.0.1:34641/zot-test to /tmp/oci-dest-repo-test188818991/zot-test/.sync/73237d80-4b5d-46a6-b874-08c62d10a71a/zot-test:invalid"}
2021-11-26T21:16:28.9061953Z {"level":"error","error":"initializing source docker://127.0.0.1:34641/zot-test:invalid: pinging container registry 127.0.0.1:34641: Get \"https://127.0.0.1:34641/v2/\": x509: certificate signed by unknown authority","goroutine":881,"caller":"github.com/anuvu/zot/pkg/api/routes.go:1281","time":"2021-11-26T21:15:51.827258762Z","message":"error encounter while syncing image zot-test:invalid"}
2021-11-26T21:16:28.9063713Z 2021/11/26 21:15:51 http: TLS handshake error from 127.0.0.1:54910: remote error: tls: bad certificate
2021-11-26T21:16:28.9066001Z {"level":"info","module":"http","clientIP":"127.0.0.1:37390","method":"GET","path":"/v2/zot-test/manifests/invalid","statusCode":404,"latency":"31.508609ms","bodySize":226,"headers":{"Accept-Encoding":["gzip"],"User-Agent":["go-resty/1.12.0 (https://github.com/go-resty/resty)"]},"goroutine":881,"caller":"github.com/anuvu/zot/pkg/api/session.go:104","time":"2021-11-26T21:15:51.827640859Z","message":"HTTP API"}
2021-11-26T21:16:28.9068217Z ✔✔{"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/api/routes.go:1265","time":"2021-11-26T21:15:51.829328949Z","message":"image not found, trying to get image invalid:0.0.1 by syncing on demand"}
2021-11-26T21:16:28.9069736Z {"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/extensions.go:129","time":"2021-11-26T21:15:51.829483548Z","message":"syncing image invalid:0.0.1"}
2021-11-26T21:16:28.9071193Z {"level":"debug","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/sync.go:425","time":"2021-11-26T21:15:51.829570148Z","message":"getting local context"}
2021-11-26T21:16:28.9073309Z {"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/on_demand.go:55","time":"2021-11-26T21:15:51.829670547Z","message":"syncing on demand with https://127.0.0.1:34641"}
2021-11-26T21:16:28.9076154Z {"level":"info","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/on_demand.go:100","time":"2021-11-26T21:15:51.830078845Z","message":"copying image 127.0.0.1:34641/invalid:0.0.1 to /tmp/oci-dest-repo-test188818991/invalid/.sync/da445280-4ea3-4ebb-bbfa-7cf4b889ecbe/invalid"}
2021-11-26T21:16:28.9077888Z 2021/11/26 21:15:51 http: TLS handshake error from 127.0.0.1:54912: remote error: tls: bad certificate
2021-11-26T21:16:28.9078649Z 2021/11/26 21:15:51 http: TLS handshake error from 127.0.0.1:54914: remote error: tls: bad certificate
2021-11-26T21:16:28.9081688Z {"level":"error","error":"initializing source docker://127.0.0.1:34641/invalid:0.0.1: pinging container registry 127.0.0.1:34641: Get \"https://127.0.0.1:34641/v2/\": x509: certificate signed by unknown authority","goroutine":881,"caller":"github.com/anuvu/zot/pkg/extensions/sync/on_demand.go:113","time":"2021-11-26T21:15:51.859692665Z","message":"error while copying image 127.0.0.1:34641/invalid to /tmp/oci-dest-repo-test188818991/invalid/.sync/da445280-4ea3-4ebb-bbfa-7cf4b889ecbe/invalid:0.0.1"}
2021-11-26T21:16:28.9085703Z {"level":"error","error":"initializing source docker://127.0.0.1:34641/invalid:0.0.1: pinging container registry 127.0.0.1:34641: Get \"https://127.0.0.1:34641/v2/\": x509: certificate signed by unknown authority","goroutine":881,"caller":"github.com/anuvu/zot/pkg/api/routes.go:1269","time":"2021-11-26T21:15:51.860121262Z","message":"error encounter while syncing image invalid:0.0.1"}
2021-11-26T21:16:28.9089167Z {"level":"info","module":"http","clientIP":"127.0.0.1:37390","method":"GET","path":"/v2/invalid/manifests/0.0.1","statusCode":404,"latency":"31.029111ms","bodySize":214,"headers":{"Accept-Encoding":["gzip"],"User-Agent":["go-resty/1.12.0 (https://github.com/go-resty/resty)"]},"goroutine":881,"caller":"github.com/anuvu/zot/pkg/api/session.go:104","time":"2021-11-26T21:15:51.860374761Z","message":"HTTP API"}
2021-11-26T21:16:28.9090731Z ✔✔
2021-11-26T21:16:28.9090918Z 
2021-11-26T21:16:28.9091110Z 
2021-11-26T21:16:28.9091435Z 64 total assertions
2021-11-26T21:16:28.9091688Z 
2021-11-26T21:16:28.9092136Z     testing.go:1092: race detected during execution of test
2021-11-26T21:16:28.9092832Z --- FAIL: TestSyncBadTLS (2.65s)
`

**Comment by adodon2go** [comment]
Run the build 8 times and it passes (original issue did not reproduce). 
I will revert pkg/extensions/sync/sync_test.go from Sebi's PR (https://github.com/anuvu/zot/pull/298/files#diff-ec4429d84169e5b537481e07ee8acf67079a9435704fb07cd7e4631a97347ec0)  that fixes the DATA RACE I saw above. (in order to improve test coverage that I previously had)

**Comment by adodon2go** [comment]
PR is ready to be merged.

**Review by rchincha — APPROVED** [review]
lgtm

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
