### PR TITLE
docs: fix Makefile

### PR DESCRIPTION
**Pull request by rchincha**

### CODE REVIEW

**Comment by tych0** [comment]
It would be nice to have a way to build the binary without swag, even if some of the stuff (e.g. docs or whatever) wouldn't work.

**Comment by rchincha** [comment]
> 
> 
> It would be nice to have a way to build the binary without swag, even if some of the stuff (e.g. docs or whatever) wouldn't work.

The bits in the docs/ dir are autogenerated. We can probably fix this with bazel.

**Comment by tych0** [comment]
Are you sure they don't? per my comment above, I think the PHONY target indirection will cause them to be rebuilt.

**Comment by rchincha** [comment]
> 
> 
> Are you sure they don't? per my comment above, I think the PHONY target indirection will cause them to be rebuilt.

PHONY(doc) depends on real(docs/doc.go), so yes that target is evaluated, but real target will not be rebuilt. Best to try out this patch.

**Comment by tych0** [comment]
On Thu, Aug 29, 2019 at 11:58:37AM -0700, Ramkumar Chinchani wrote:
> > 
> > 
> > Are you sure they don't? per my comment above, I think the PHONY target indirection will cause them to be rebuilt.
> 
> PHONY(doc) depends on real(docs/doc.go), so yes that target is evaluated, but real target will not be rebuilt. Best to try out this patch.

Ah, yep, I see. It still would be nice to have a way to build the
binary without having to install "swag", but otherwise this LGTM.

**Pull request merged**
