### PR TITLE
cli: add option to ignore TLS verification

### PR DESCRIPTION
**Pull request by tsnaik**
adds a property in config : "verify-tls". It allows user to make unsecured HTTPS connections by skipping TLS certificate verification

```console
$ zot config add local https://localhost:8080         
$ zot config local -l                       
url = http://localhost:8080
showspinner = true
verify-tls = true
$ zot config local verify-tls false
$ zot config local -l                       
url = https://localhost:8080
showspinner = true
verify-tls = false
```

### CODE REVIEW

**Comment by mikemccracken** [comment]
this looks fine to me, it'd be convenient for my usual use case if there was a corresponding cmdline option so I don't have to separately set config...

**Comment by tsnaik** [comment]
> this looks fine to me, it'd be convenient for my usual use case if there was a corresponding cmdline option so I don't have to separately set config...

@mikemccracken, we have discussed that option but chose to go not go with that for UX simplicity. @rchincha can add perhaps

**Comment by rchincha** [comment]
> 
> 
> this looks fine to me, it'd be convenient for my usual use case if there was a corresponding cmdline option so I don't have to separately set config...

config modeled after git-style config and is one-time, and keeping one way is less confusing.

**Comment by mikemccracken** [comment]
> > this looks fine to me, it'd be convenient for my usual use case if there was a corresponding cmdline option so I don't have to separately set config...
> 
> config modeled after git-style config and is one-time, and keeping one way is less confusing.

ok, it's your call :)

**Pull request merged**
